# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel = true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version = 1.18.2
fabric_loader_version = 0.18.4
fabric_api_version = 0.77.0+1.18.2
loom_version = 1.17-SNAPSHOT

# https://parchmentmc.org/docs/getting-started
parchment_version = 2022.11.06

# Mod Properties
mod_version = 1.0
maven_group = com.jerrylu086.astral_bridge
archive_base_name = astral_bridge-fabric

# Dependencies
porting_lib_version = 1.2.1584-beta+1.18.2
forge_config_api_port_version = 3.2.4
create_version = 0.5.1-f-build.1415+mc1.18.2
ccaa_version = 1.18.2-20230704a
trinkets_version = 3.3.1
another_furniture_version = fabric-2.1.2-1.18.2
hephaestus_version = 1.18.2-3.5.2.312
mantle_version = 1.18.2-1.9.156
star_version = 1.3
ad_astra_version = 1.0.9
cloth_config_version = 6.5.102
teamreborn_energy_version = 2.2.0

modmenu_version = 3.2.5
rei_version = 8.4.778
emi_version = 0.7.3+1.18.2
lazydfu_version = 0.1.2

